[package]
name = "burin-core"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
geo = "0.33.1"
hex = "0.4.3"
libm = "0.2.16"
robust = "1.2.0"
rstar = "0.12"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
sha2 = "0.11.0"
thiserror = "2.0.20"
